version: '3.8'

services:
  data-provider-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=YourPassword123
      - DB_DATABASE=ATXDADOS
      - GRAPHQL_PLAYGROUND=true
      - GRAPHQL_DEBUG=true
      - LOG_LEVEL=debug
    depends_on:
      - sqlserver
    networks:
      - microservices-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./scripts:/scripts
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  sqlserver_data:

