USE [ATXDADOS]
GO

/****** Object:  Table [dbo].[ENTIDADES]    Script Date: 08/09/2025 10:57:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ENTIDADES](
	[ID_ENTIDADE] [int] IDENTITY(1,1) NOT NULL,
	[ID_FILIAL] [smallint] NOT NULL,
	[ID_CIDADES] [smallint] NULL,
	[ID_EMPRESASENTIDADES] [smallint] NULL,
	[CODIGOENTIDADE] [varchar](13) NULL,
	[NOMEENTIDADE] [varchar](50) NULL,
	[RAZAOSOCIALENTIDADE] [varchar](70) NULL,
	[DTACADASTRO] [smalldatetime] NULL,
	[PESSOA] [tinyint] NULL,
	[ENDERECO] [varchar](70) NULL,
	[BAIRRO] [varchar](35) NULL,
	[CEP] [varchar](8) NULL,
	[CNPJCPF] [varchar](14) NULL,
	[IERG] [varchar](14) NULL,
	[ORGAOEMISSORRG] [varchar](8) NULL,
	[FONE] [varchar](10) NULL,
	[CELULAR] [varchar](11) NULL,
	[FAX] [varchar](10) NULL,
	[EMAIL] [varchar](40) NULL,
	[CATEGORIA] [varchar](1) NULL,
	[DIAVCTO] [tinyint] NULL,
	[PRAZOOPERACIONAL] [int] NULL,
	[DTANASCIMENTO] [smalldatetime] NULL,
	[LIMITE] [real] NULL,
	[EMITIRICMS] [bit] NOT NULL,
	[CARENCIA] [tinyint] NULL,
	[CXPOSTAL] [varchar](5) NULL,
	[CODIGOBARRA] [varchar](20) NULL,
	[CARTAOMAGNETICO] [varchar](16) NULL,
	[LISTANEGRA] [bit] NOT NULL,
	[TIPOPGTO] [tinyint] NULL,
	[EMITIRFATURA] [bit] NOT NULL,
	[EMITIRBOLETO] [bit] NOT NULL,
	[EMITIRDUPLICATA] [bit] NOT NULL,
	[INCLUIRJUROFATURA] [bit] NOT NULL,
	[CONTATO] [varchar](30) NULL,
	[CLIENTE_FORNECEDOR] [tinyint] NULL,
	[DESCONTO] [bit] NOT NULL,
	[OBS] [varchar](255) NULL,
	[OBSCOMPROVANTE] [varchar](500) NULL,
	[PGTO_PRAZO] [bit] NOT NULL,
	[PGTO_CHQ_PRE] [bit] NOT NULL,
	[PGTO_CONV_C_CREDITO] [bit] NOT NULL,
	[PGTO_C_DEBITO] [bit] NOT NULL,
	[PGTO_C_FRETE] [bit] NOT NULL,
	[PGTO_DEP_BANCARIO] [bit] NOT NULL,
	[PGTO_CHQ_VISTA] [bit] NOT NULL,
	[PGTO_M_DIVERSAS] [bit] NOT NULL,
	[PGTO_OUTROS] [bit] NOT NULL,
	[DESC_DINHEIRO] [bit] NOT NULL,
	[DESC_PRAZO] [bit] NOT NULL,
	[DESC_CHQ_PRE] [bit] NOT NULL,
	[DESC_CONV_C_CREDITO] [bit] NOT NULL,
	[DESC_C_DEBITO] [bit] NOT NULL,
	[DESC_C_FRETE] [bit] NOT NULL,
	[DESC_DEP_BANCARIO] [bit] NOT NULL,
	[DESC_CHQ_VISTA] [bit] NOT NULL,
	[DESC_M_DIVERSAS] [bit] NOT NULL,
	[DESC_OUTROS] [bit] NOT NULL,
	[DIAVCTOOPCIONAL] [tinyint] NULL,
	[VLRFIXO] [tinyint] NULL,
	[ATIVO] [bit] NOT NULL,
	[VLRBRINDE] [real] NULL,
	[SENHA] [varchar](100) NULL,
	[DATAREPL] [datetime] NULL,
	[PGTO_CTFIDELIDADE] [bit] NOT NULL,
	[DESC_CTFIDELIDADE] [bit] NOT NULL,
	[FORCAODOMETRO] [bit] NULL,
	[FORCAPLACA] [bit] NULL,
	[ST_ENDCOBRANCA] [tinyint] NULL,
	[ENDERECOCOBRANCA] [varchar](70) NULL,
	[BAIRROCOBRANCA] [varchar](35) NULL,
	[CEPCOBRANCA] [varchar](8) NULL,
	[ID_CIDADESCOBRANCA] [smallint] NULL,
	[SALDOLITROS] [real] NULL,
	[IEFISICA] [varchar](20) NULL,
	[FORCAREQUISICAO] [bit] NULL,
	[EMAIL_COBRANCA] [varchar](250) NULL,
	[ENVIAREMAIL] [bit] NULL,
	[VENDACONSUMIDOR] [bit] NULL,
	[Simples] [bit] NULL,
	[FORCABIOMETRIA] [bit] NULL,
	[ULTALTERACAO] [smalldatetime] NULL,
	[COD_SCANC] [varchar](5) NULL,
	[DIAVCTOOPCIONAL2] [tinyint] NULL,
	[ID_FORMASPGTOCARTAFRETE] [smallint] NULL,
	[TAXACARTAFRETE] [bit] NULL,
	[ID_FILIALPGTO] [smallint] NULL,
	[ID_OUTRASFORMASPGTO] [smallint] NULL,
	[TROCACHEQUES] [bit] NULL,
	[PGTO_DINHEIRO] [bit] NULL,
	[DESCBOLETO] [real] NULL,
	[NRODIASBOLETO] [smallint] NULL,
	[EMISSAOFISCAL] [tinyint] NULL,
	[NomeMae] [varchar](50) NULL,
	[NomePai] [varchar](50) NULL,
	[NUMERO] [varchar](20) NULL,
	[ID_CONDICOESPGTO] [int] NULL,
	[RECEBEVALE] [bit] NULL,
	[VERIFICALIMITE] [bit] NULL,
	[ID_ENTIDADEGRUPO] [int] NULL,
	[NFAUTO] [bit] NULL,
	[BXBRINDESNEGATIVOS] [bit] NULL,
	[COD_INSTALACAOSIMPTRR] [varchar](15) NULL,
	[COD_ATIVIDADESIMPTRR] [varchar](15) NULL,
	[CATEGORIA_ANP] [varchar](15) NULL,
	[FORCAFATANT] [bit] NULL,
	[TPARREDONDAMENTOECF] [bit] NULL,
	[DESTACARNORMA480] [bit] NOT NULL,
	[NORMA480_ABATERVLR] [bit] NOT NULL,
	[FORCAPLACACADASTRADA] [bit] NOT NULL,
	[CLIENTENOSERASA] [bit] NOT NULL,
	[FORCARNFE] [bit] NULL,
	[ISSRF] [bit] NULL,
	[REGALT] [bit] NULL,
	[ENVIARXMLPDF] [bit] NULL,
	[RETEM_IRRF] [bit] NULL,
	[RETEM_ISS] [bit] NULL,
	[RETEM_INSS] [bit] NULL,
	[RETEM_PCC] [bit] NULL,
	[IND_NATUREZA] [smallint] NULL,
	[GERACOMISSAO] [bit] NULL,
	[FORCAR_XPID] [bit] NULL,
	[SALDOINTEGRACAO] [money] NULL,
	[BX_DINHEIRO] [bit] NOT NULL,
	[BX_CHQ_PRE] [bit] NOT NULL,
	[BX_CONV_C_CREDITO] [bit] NOT NULL,
	[BX_C_DEBITO] [bit] NOT NULL,
	[BX_C_FRETE] [bit] NOT NULL,
	[BX_DEP_BANCARIO] [bit] NOT NULL,
	[BX_CHQ_VISTA] [bit] NOT NULL,
	[BX_M_DIVERSAS] [bit] NOT NULL,
	[BX_OUTROS] [bit] NOT NULL,
	[BX_CREDITO] [bit] NOT NULL,
	[CONSUMIDOR_FINAL] [int] NULL,
	[TIPO_OPERACAO] [int] NULL,
	[TIPO_CONTRIBUINTE] [int] NULL,
	[FORCAMOTORISTA] [bit] NULL,
	[ID_LISTAPRECOS] [smallint] NULL,
	[IMP_NT_PROM_PRAZO] [bit] NOT NULL,
	[ID_GRUPOENTIDADES] [int] NULL,
	[AVISOCOMPRA] [bit] NULL,
	[USAR_DEPARTAMENTO] [bit] NULL,
	[FORCARDEPARTAMENTO] [bit] NULL,
	[PROTESTARBOLETO] [bit] NULL,
	[CADASTRO_GERENCIAL] [bit] NULL,
	[EMAIL_NFE_NFCE] [varchar](250) NULL,
	[ENVIAR_EMAIL_NFCE] [bit] NULL,
	[FORCAFROTA] [bit] NULL,
	[VERIFICACARENCIA] [bit] NULL,
	[VALIDARCOMBUSTIVEL] [bit] NULL,
	[NAO_EMITIR_CUPOM_BONUS] [bit] NOT NULL,
	[PERC_LIMITE_BAIXO] [money] NULL,
	[AVISO_LIMITE_BAIXO] [bit] NOT NULL,
	[ANALISAR_NCM] [bit] NULL,
	[INCLUIR_OBS_EMISSAO_FATURA] [bit] NOT NULL,
	[SEXO] [tinyint] NULL,
	[NAO_PERM_ALT_EMI_FISCAL_VENDA] [bit] NULL,
	[USARASSINATURAELETRONICA] [bit] NOT NULL,
	[NAOCALCJUROS] [bit] NULL,
	[PRAZOMAXIMOCHEQUE] [int] NOT NULL,
	[DIAVCTO_VALE] [tinyint] NULL,
	[NEGATIVARBOLETO] [bit] NOT NULL,
	[DIAVCTOOPCIONAL_VALE] [tinyint] NULL,
	[DIAVCTOOPCIONAL2_VALE] [tinyint] NULL,
	[PRAZOOPERACIONAL_VALE] [int] NULL,
	[CARENCIA_VALE] [tinyint] NULL,
	[LIMITE_VALE] [real] NULL,
	[LIMITE_VALE_SEPARADO] [bit] NULL,
	[TIPO_LIMITE_VALE] [tinyint] NULL,
	[NAOPONTUACLUBFIDELIDADE] [bit] NULL,
	[PONTUAPOSTOAKI] [bit] NOT NULL,
	[LIMITES_GRUPO_ECONOMICO] [bit] NULL,
	[TICKET_LOG] [bit] NULL,
	[PGTO_PIX] [bit] NULL,
	[DESC_PIX] [bit] NULL,
	[NAO_USAR_LP_VENDA] [bit] NULL,
	[FORCARMOTCADASTRADO] [bit] NULL,
	[PGTO_CREDITO_DINHEIRO] [bit] NOT NULL,
	[PGTO_CREDITO_CHEQUEPRE] [bit] NOT NULL,
	[PGTO_CREDITO_CONVENIO] [bit] NOT NULL,
	[PGTO_CREDITO_DEBITO] [bit] NOT NULL,
	[PGTO_CREDITO_CARTAFRETE] [bit] NOT NULL,
	[PGTO_CREDITO_DEPOSITO] [bit] NOT NULL,
	[PGTO_CREDITO_CHEQUEAVISTA] [bit] NOT NULL,
	[PGTO_CREDITO_MOEDASDIVERSAS] [bit] NOT NULL,
	[PGTO_CREDITO_OUTROS] [bit] NOT NULL,
	[NAOENVIAREMAILPROM] [bit] NOT NULL,
	[PONTUAMEUPOSTO] [bit] NOT NULL,
	[FIDELIDADE_TERCEIRO] [tinyint] NULL,
	[TROCO_DINHEIRO] [bit] NULL,
	[TROCO_CHQ_TERCEIRO] [bit] NULL,
	[TROCO_CHQ_PROPRIO] [bit] NULL,
	[TROCO_CREDITO] [bit] NULL,
	[TROCO_OUTROS] [bit] NULL,
	[TROCO_M_DIVERSAS] [bit] NULL,
	[TROCO_DEPOSITO] [bit] NULL,
	[PONTUAVALUE4U] [bit] NULL,
	[NRO_DIAS_NEGATIVACAO] [int] NULL,
 CONSTRAINT [PK_ENTIDADES] PRIMARY KEY CLUSTERED 
(
	[ID_ENTIDADE] ASC,
	[ID_FILIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [LIMITE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [EMITIRICMS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [LISTANEGRA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [EMITIRFATURA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [EMITIRBOLETO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [EMITIRDUPLICATA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [INCLUIRJUROFATURA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESCONTO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_PRAZO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_CHQ_PRE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_CONV_C_CREDITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_C_DEBITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_C_FRETE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_DEP_BANCARIO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_CHQ_VISTA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_M_DIVERSAS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_OUTROS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_DINHEIRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_PRAZO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_CHQ_PRE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_CONV_C_CREDITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_C_DEBITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_C_FRETE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_DEP_BANCARIO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_CHQ_VISTA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_M_DIVERSAS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_OUTROS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (4) FOR [VLRFIXO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (1) FOR [ATIVO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [VLRBRINDE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (getdate()) FOR [DATAREPL]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [PGTO_CTFIDELIDADE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESC_CTFIDELIDADE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [FORCAODOMETRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [FORCAPLACA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (1) FOR [ST_ENDCOBRANCA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [SALDOLITROS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [FORCAREQUISICAO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [ENVIAREMAIL]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [VENDACONSUMIDOR]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [FORCABIOMETRIA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (null) FOR [ID_OUTRASFORMASPGTO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [TROCACHEQUES]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (1) FOR [PGTO_DINHEIRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESCBOLETO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [EMISSAOFISCAL]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [RECEBEVALE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (1) FOR [VERIFICALIMITE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (1) FOR [BXBRINDESNEGATIVOS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [FORCAFATANT]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [TPARREDONDAMENTOECF]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [DESTACARNORMA480]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [NORMA480_ABATERVLR]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [FORCAPLACACADASTRADA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [CLIENTENOSERASA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [FORCARNFE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [ISSRF]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [REGALT]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (0) FOR [ENVIARXMLPDF]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT (1) FOR [GERACOMISSAO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_DINHEIRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_CHQ_PRE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_CONV_C_CREDITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_C_DEBITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_C_FRETE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_DEP_BANCARIO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_CHQ_VISTA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_M_DIVERSAS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_OUTROS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [BX_CREDITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [CONSUMIDOR_FINAL]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TIPO_OPERACAO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TIPO_CONTRIBUINTE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [IMP_NT_PROM_PRAZO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ('') FOR [EMAIL_NFE_NFCE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [ENVIAR_EMAIL_NFCE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [FORCAFROTA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [VERIFICACARENCIA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [VALIDARCOMBUSTIVEL]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [NAO_EMITIR_CUPOM_BONUS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [AVISO_LIMITE_BAIXO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [INCLUIR_OBS_EMISSAO_FATURA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [USARASSINATURAELETRONICA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [PRAZOMAXIMOCHEQUE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [NEGATIVARBOLETO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [PONTUAPOSTOAKI]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_PIX]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [DESC_PIX]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [NAO_USAR_LP_VENDA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [FORCARMOTCADASTRADO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_DINHEIRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_CHEQUEPRE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_CONVENIO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_DEBITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_CARTAFRETE]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_DEPOSITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_CHEQUEAVISTA]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_MOEDASDIVERSAS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((1)) FOR [PGTO_CREDITO_OUTROS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [NAOENVIAREMAILPROM]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [PONTUAMEUPOSTO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [FIDELIDADE_TERCEIRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TROCO_DINHEIRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TROCO_CHQ_TERCEIRO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TROCO_CHQ_PROPRIO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TROCO_CREDITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TROCO_OUTROS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TROCO_M_DIVERSAS]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [TROCO_DEPOSITO]
GO

ALTER TABLE [dbo].[ENTIDADES] ADD  DEFAULT ((0)) FOR [PONTUAVALUE4U]
GO

ALTER TABLE [dbo].[ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ENTIDADE_REFERENCE_CIDADES] FOREIGN KEY([ID_CIDADES], [ID_FILIAL])
REFERENCES [dbo].[CIDADES] ([ID_CIDADES], [ID_FILIAL])
GO

ALTER TABLE [dbo].[ENTIDADES] CHECK CONSTRAINT [FK_ENTIDADE_REFERENCE_CIDADES]
GO

ALTER TABLE [dbo].[ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ENTIDADE_REFERENCE_EMPRESAS] FOREIGN KEY([ID_EMPRESASENTIDADES], [ID_FILIAL])
REFERENCES [dbo].[EMPRESASENTIDADES] ([ID_EMPRESASENTIDADES], [ID_FILIAL])
GO

ALTER TABLE [dbo].[ENTIDADES] CHECK CONSTRAINT [FK_ENTIDADE_REFERENCE_EMPRESAS]
GO

ALTER TABLE [dbo].[ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ENTIDADES_REFERENCE_FPGTOCF] FOREIGN KEY([ID_FORMASPGTOCARTAFRETE], [ID_FILIAL])
REFERENCES [dbo].[FORMASPGTOCARTAFRETE] ([ID_FORMASPGTOCARTAFRETE], [ID_FILIAL])
GO

ALTER TABLE [dbo].[ENTIDADES] CHECK CONSTRAINT [FK_ENTIDADES_REFERENCE_FPGTOCF]
GO

ALTER TABLE [dbo].[ENTIDADES]  WITH CHECK ADD  CONSTRAINT [FK_ENTIDADES_REFERENCE_OUTRAS_F_PGTO] FOREIGN KEY([ID_OUTRASFORMASPGTO], [ID_FILIAL])
REFERENCES [dbo].[OUTRASFORMASPGTO] ([ID_OUTRASFORMASPGTO], [ID_FILIAL])
GO

ALTER TABLE [dbo].[ENTIDADES] CHECK CONSTRAINT [FK_ENTIDADES_REFERENCE_OUTRAS_F_PGTO]
GO


