USE [ATXDADOS]
GO

/****** Object:  Table [dbo].[PRODUTOS]    Script Date: 08/09/2025 10:57:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTOS](
	[ID_PRODUTOS] [int] IDENTITY(1,1) NOT NULL,
	[ID_FILIAL] [smallint] NOT NULL,
	[ID_ENTIDADE] [int] NULL,
	[ID_LOCALVENDAS] [smallint] NULL,
	[ID_GRUPOPRODUTOS] [smallint] NOT NULL,
	[ID_MARCAS] [smallint] NULL,
	[CODIGOPRODUTO] [varchar](15) NULL,
	[NOMEPRODUTO] [varchar](50) NOT NULL,
	[UNIDADE] [varchar](4) NULL,
	[TIPOTRIBUTACAO] [tinyint] NULL,
	[REDUCAOICMS] [real] NULL,
	[CODIGOBARRAPRODUTO] [varchar](20) NULL,
	[ORIGEMPRODUTO] [tinyint] NULL,
	[MARGEMLUCRO] [real] NULL,
	[ALIQUOTAIPI] [real] NULL,
	[ALIQUOTAISS] [real] NULL,
	[ALIQUOTAICMS] [real] NULL,
	[PRODUTOCOMPOSTO] [bit] NOT NULL,
	[CUSTOMEDIO] [decimal](18, 6) NULL,
	[CUSTOGERENCIAL] [real] NULL,
	[MARGEMSUBST] [real] NULL,
	[ITEMESPECIAL] [tinyint] NULL,
	[QTDETOTAL] [real] NULL,
	[DATACADASTRO] [smalldatetime] NULL,
	[DESCONTOMAXIMO] [real] NULL,
	[NROLMCATUAL] [int] NULL,
	[CUSTOMEDIOCOMICMS] [decimal](18, 6) NULL,
	[ATIVO] [bit] NOT NULL,
	[TIPOCOMBUSTIVEL] [tinyint] NULL,
	[MEDIDACOMBUSTIVEL] [tinyint] NULL,
	[VLRBRINDEVENDA] [real] NULL,
	[VLRBRINDECOMPRA] [real] NULL,
	[DATAREPL] [datetime] NULL,
	[CUSTOMEDIOSUBST] [real] NULL,
	[ID_TEXTOFISCAL] [smallint] NULL,
	[FRACIONAVEL] [bit] NULL,
	[ID_CFOPENTR] [smallint] NULL,
	[ID_CFOPSAIDA] [smallint] NULL,
	[ID_CFOPENTREX] [smallint] NULL,
	[ID_CFOPENTRUF] [smallint] NULL,
	[ID_CFOPSAIDAUF] [smallint] NULL,
	[ID_CFOPSAIDAEX] [smallint] NULL,
	[ULTALTERACAO] [smalldatetime] NULL,
	[VCTOKM] [int] NULL,
	[VCTODIAS] [int] NULL,
	[ULTVLRENTRADA] [real] NULL,
	[PENVLRENTRADA] [real] NULL,
	[PIS_COFINS] [bit] NULL,
	[ID_CFOPFATANTECIPADO] [smallint] NULL,
	[ID_CFOPREMESSAFAT] [smallint] NULL,
	[ID_CFOPFATANTECIPADOUF] [smallint] NULL,
	[ID_CFOPREMESSAFATUF] [smallint] NULL,
	[GNV] [bit] NULL,
	[QTDEENTRADA] [real] NULL,
	[CODIGOANP] [varchar](20) NULL,
	[INCIDENCIACFOP] [smallint] NULL,
	[ID_PLANODECONTAS] [int] NULL,
	[SEFAZ] [varchar](14) NULL,
	[QTDENEGATIVA] [bit] NULL,
	[DESCONTOMAXCAD] [real] NULL,
	[PESOPORLITRO] [real] NULL,
	[NCM] [varchar](8) NULL,
	[EXTIPI] [varchar](3) NULL,
	[GENERO] [tinyint] NULL,
	[MODBC] [tinyint] NULL,
	[MODBCST] [tinyint] NULL,
	[CODIF] [varchar](22) NULL,
	[TECLAATALHO] [int] NULL,
	[APELIDO] [varchar](15) NULL,
	[ID_ARTIGOS] [int] NULL,
	[ID_SUBGRUPOS] [int] NULL,
	[IAT] [tinyint] NULL,
	[IPPT] [tinyint] NULL,
	[PFINSEFAZ] [real] NULL,
	[LOCALIZACAO] [varchar](30) NULL,
	[MARGEMBR] [real] NULL,
	[ID_CFOPPRESTREGDENTRO] [int] NULL,
	[ID_CFOPPRESTREGFORA] [int] NULL,
	[ABAIXOCUSTO] [bit] NOT NULL,
	[CST_PIS] [tinyint] NULL,
	[CST_COFINS] [tinyint] NULL,
	[ENCERRANTE] [money] NULL,
	[CONT_ENCERRANTE] [bit] NULL,
	[REGALT] [bit] NULL,
	[CSOSN] [smallint] NULL,
	[KIT] [bit] NOT NULL,
	[QTDEANP] [decimal](19, 3) NULL,
	[CUSTOMARKA] [decimal](19, 3) NOT NULL,
	[PRODMARKA] [varchar](100) NULL,
	[PERCSTPISCOFINS] [smallmoney] NULL,
	[MARGEMMARKUP] [real] NULL,
	[NATREC] [varchar](4) NULL,
	[CST_PIS_ENT] [tinyint] NULL,
	[CST_COFINS_ENT] [tinyint] NULL,
	[COD_LISTA_SERVICO] [varchar](15) NULL,
	[TIPOIPI] [tinyint] NULL,
	[CSTENTRADA] [tinyint] NULL,
	[TAB_COD_NAT_REC] [tinyint] NULL,
	[COD_IDENTIFICADOR] [tinyint] NULL,
	[PESO_BRUTO_POR_UNIDADE] [decimal](15, 2) NOT NULL,
	[ALIQPIS] [real] NULL,
	[ALIQCOFINS] [real] NULL,
	[IRRF] [real] NULL,
	[RETEM_ISS] [bit] NULL,
	[RETEM_PCC] [bit] NULL,
	[ALIQINSS] [real] NULL,
	[REDUCAO_INSS] [real] NULL,
	[TAXA_CONVERSAO_VLR_TRIB] [real] NULL,
	[UNIDADE_TRIB] [varchar](5) NULL,
	[COD_TIM] [int] NULL,
	[TIPOCUSTO] [tinyint] NULL,
	[PRODUTO_LMC_WS] [smallint] NULL,
	[CEST] [varchar](15) NULL,
	[ID_CFOPsaidaOutraUF] [int] NULL,
	[COMISSAOREAIS] [bit] NULL,
	[ORDEMNUMEROLIVRO] [int] NULL,
	[BALANCA] [bit] NULL,
	[ALIQFECOP] [real] NULL,
	[DESCONTOMAXIMORESTRITO] [float] NULL,
	[CBENEF] [varchar](10) NOT NULL,
	[CLASSRECEITA] [tinyint] NOT NULL,
	[ULTALTSYSTAX] [smalldatetime] NULL,
	[TIPOPRODUTO] [tinyint] NULL,
	[NAO_FORCAR_COD_BARRAS_VENDA] [bit] NULL,
	[MARGEMMINIMA] [real] NULL,
	[ULTALTIMENDES] [smalldatetime] NULL,
	[ULTALTTRIBUTOFACIL] [smalldatetime] NULL,
	[ID_CFOPENTRTRANSF] [smallint] NULL,
	[ID_CFOPSAITRANSF] [smallint] NULL,
	[ID_CFOPENTRTRANSFUF] [smallint] NULL,
	[ID_CFOPSAITRANSFUF] [smallint] NULL,
	[ID_VIBRA] [varchar](15) NULL,
	[TIPO_PRODUTO_VIBRA] [tinyint] NULL,
	[CODIGOPREMMIA] [varchar](20) NULL,
	[ID_IPIRANGA] [varchar](15) NULL,
	[TIPO_PRODUTO_IPIRANGA] [tinyint] NULL,
	[BRINDE_QTDE_MINIMA] [float] NOT NULL,
	[ULTALTRESSARCETAX] [smalldatetime] NULL,
	[CODIGO_INTERNO_PROMOCAO_VIBRA] [int] NULL,
	[REBATE_VIBRA] [float] NULL,
	[PONTOS_PREMMIA] [int] NULL,
	[TIPOTRIBUTACAO_TRANSF] [tinyint] NULL,
	[ALIQUOTAICMS_TRANSF] [real] NULL,
	[RED_DIF_ICMS_TRANSF] [real] NULL,
	[CBENEF_TRANSF] [varchar](10) NULL,
 CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUTOS] ASC,
	[ID_FILIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [REDUCAOICMS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [MARGEMLUCRO]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [ALIQUOTAIPI]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [ALIQUOTAISS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [ALIQUOTAICMS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [PRODUTOCOMPOSTO]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [CUSTOGERENCIAL]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [MARGEMSUBST]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [QTDETOTAL]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [DESCONTOMAXIMO]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [NROLMCATUAL]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (1) FOR [ATIVO]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [TIPOCOMBUSTIVEL]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [MEDIDACOMBUSTIVEL]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [VLRBRINDEVENDA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [VLRBRINDECOMPRA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (getdate()) FOR [DATAREPL]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [CUSTOMEDIOSUBST]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (1) FOR [FRACIONAVEL]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [ULTVLRENTRADA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [PENVLRENTRADA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [PIS_COFINS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [GNV]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  CONSTRAINT [DF__PRODUTOS__QTDEEN__0DA4EB0F]  DEFAULT ((0)) FOR [QTDEENTRADA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (1) FOR [IAT]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (1) FOR [IPPT]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (1) FOR [ABAIXOCUSTO]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [CST_PIS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [CST_COFINS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [REGALT]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [KIT]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [CUSTOMARKA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT ('') FOR [PRODMARKA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [PERCSTPISCOFINS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [TIPOIPI]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [CSTENTRADA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (1) FOR [PESO_BRUTO_POR_UNIDADE]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [ALIQPIS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT (0) FOR [ALIQCOFINS]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT ('') FOR [CBENEF]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT ((0)) FOR [CLASSRECEITA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT ((0)) FOR [NAO_FORCAR_COD_BARRAS_VENDA]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT ((0)) FOR [BRINDE_QTDE_MINIMA]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_CFOPENTRTRANSF] FOREIGN KEY([ID_CFOPENTRTRANSF], [ID_FILIAL])
REFERENCES [dbo].[CFOP] ([ID_CFOP], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_CFOPENTRTRANSF]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_CFOPENTRTRANSFUF] FOREIGN KEY([ID_CFOPENTRTRANSFUF], [ID_FILIAL])
REFERENCES [dbo].[CFOP] ([ID_CFOP], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_CFOPENTRTRANSFUF]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_CFOPSAITRANSF] FOREIGN KEY([ID_CFOPSAITRANSF], [ID_FILIAL])
REFERENCES [dbo].[CFOP] ([ID_CFOP], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_CFOPSAITRANSF]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_CFOPSAITRANSFUF] FOREIGN KEY([ID_CFOPSAITRANSFUF], [ID_FILIAL])
REFERENCES [dbo].[CFOP] ([ID_CFOP], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_CFOPSAITRANSFUF]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_REF_LV_P_LV] FOREIGN KEY([ID_LOCALVENDAS], [ID_FILIAL])
REFERENCES [dbo].[LOCALVENDAS] ([ID_LOCALVENDAS], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_REF_LV_P_LV]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_REFERENCE_ENTIDADE] FOREIGN KEY([ID_ENTIDADE], [ID_FILIAL])
REFERENCES [dbo].[ENTIDADES] ([ID_ENTIDADE], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_REFERENCE_ENTIDADE]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_REFERENCE_GRUPOPRO] FOREIGN KEY([ID_GRUPOPRODUTOS], [ID_FILIAL])
REFERENCES [dbo].[GRUPOPRODUTOS] ([ID_GRUPOPRODUTOS], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_REFERENCE_GRUPOPRO]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_REFERENCE_MARCAS] FOREIGN KEY([ID_MARCAS], [ID_FILIAL])
REFERENCES [dbo].[MARCAS] ([ID_MARCAS], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_REFERENCE_MARCAS]
GO

ALTER TABLE [dbo].[PRODUTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_REFERENCE_TEXTOFIS] FOREIGN KEY([ID_TEXTOFISCAL], [ID_FILIAL])
REFERENCES [dbo].[TEXTOFISCAL] ([ID_TEXTOFISCAL], [ID_FILIAL])
GO

ALTER TABLE [dbo].[PRODUTOS] CHECK CONSTRAINT [FK_PRODUTOS_REFERENCE_TEXTOFIS]
GO


